<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-07-01 12:29
=======
# Generated by Django 5.2.3 on 2025-07-01 14:18
>>>>>>> feae735 (Add GET and POST endpoints for volunteers)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='password',
<<<<<<< HEAD
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
=======
            field=models.CharField(blank=True, max_length=255, null=True),
>>>>>>> feae735 (Add GET and POST endpoints for volunteers)
        ),
    ]
