# Generated by Django 5.2.3 on 2025-07-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_volunteer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='motdepasse', max_length=255, null=True),
        ),
    ]
