# Generated by Django 5.2.3 on 2025-07-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adopter'),
        ('core', '0003_alter_volunteer_password'),
    ]

    operations = [
    ]
