# Generated by Django 5.2.3 on 2025-07-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0002_adopter_0003_alter_volunteer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='disponibility',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('active', 'Active'), ('inactif', 'Inactif')], default='en attente', max_length=20),
        ),
    ]
