# Generated by Django 5.2.3 on 2025-07-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_volunteer_disponibility_alter_animal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
